### ISSUE TITLE
syntax error when I try running d0read.sh

### ISSUE THREAD

**Issue by mawa85** [wiresio/lesekopf#1]
Hi, 

thanks for your work. 
I get the following syntax error when running your read script.
Do you have any idea what could cause the syntax error?

Thnaks

> $ ./d0read.sh
> ./d0read.sh: Zeile 17: 1152
> 1.8.1*05(00000674
> 1.8.1*04(00000315
> 1.8.1*03(00000072
> 1.8.1*02(00000004
> 1.8.1*01(00000004
> 1.8.1*00(00000000
> 1.8.1*99(00000000
> 1.8.1*98(00000000
> 1.8.1*97(00000000
> 1.8.1*96(00000000
> 1.8.1*95(00000000
> 1.8.1*94(00000000
> 1.8.1*93(00000000
> 1.8.1*92(00000000
> 1.8.1*91(00000000
> 1153
> 1.8.1*05(00000674
> 1.8.1*04(00000315
> 1.8.1*03(00000072
> 1.8.1*02(00000004
> 1.8.1*01(00000004
> 1.8.1*00(00000000
> 1.8.1*99(00000000
> 1.8.1*98(00000000
> 1.8.1*97(00000000
> 1.8.1*96(00000000
> 1.8.1*95(00000000
> 1.8.1*94(00000000
> 1.8.1*93(00000000
> 1.8.1*92(00000000
> 1.8.1*91(00000000: Syntaxfehler im Ausdruck. (Fehlerverursachendes Zeichen ist \"1.8.1*05(00000674
> 1.8.1*04(00000315
> 1.8.1*03(00000072
> 1.8.1*02(00000004
> 1.8.1*01(00000004
> 1.8.1*00(00000000
> 1.8.1*99(00000000
> 1.8.1*98(00000000
> 1.8.1*97(00000000
> 1.8.1*96(00000000
> 1.8.1*95(00000000
> 1.8.1*94(00000000
> 1.8.1*93(00000000
> 1.8.1*92(00000000
> 1.8.1*91(00000000
> 1153
> 1.8.1*05(00000674
> 1.8.1*04(00000315
> 1.8.1*03(00000072
> 1.8.1*02(00000004
> 1.8.1*01(00000004
> 1.8.1*00(00000000
> 1.8.1*99(00000000
> 1.8.1*98(00000000
> 1.8.1*97(00000000
> 1.8.1*96(00000000
> 1.8.1*95(00000000
> 1.8.1*94(00000000
> 1.8.1*93(00000000
> 1.8.1*92(00000000
> 1.8.1*91(00000000\").

Output of d0test

> ./d0test.sh
> /?!
> 
> /EMH4@--ITZ-G0038E
> F.F(00000000)
> 0.0.0(XXXXXXXX)
> 0.0.1(XXXXXXXX)
> 0.0.2(XXXXXXXX)
> 0.1.0(05)
> 0.1.2*05(0171201000000)
> 0.1.2*04(0171101000000)
> 0.1.2*03(1171001000000)
> 0.1.2*02(1170919110906)
> 0.1.2*01(0170822071204)
> 0.1.2*00(0000000000000)
> 0.1.2*99(0000000000000)
> 0.1.2*98(0000000000000)
> 0.1.2*97(0000000000000)
> 0.1.2*96(0000000000000)
> 0.1.2*95(0000000000000)
> 0.1.2*94(0000000000000)
> 0.1.2*93(0000000000000)
> 0.1.2*92(0000000000000)
> 0.1.2*91(0000000000000)
> 0.2.2(06002000)
> 0.9.1(0191725)
> 0.9.2(0171229)
> 1.8.0(00002053*kWh)
> 1.8.0*05(00001224*kWh)
> 1.8.0*04(00000539*kWh)
> 1.8.0*03(00000123*kWh)
> 1.8.0*02(00000006*kWh)
> 1.8.0*01(00000006*kWh)
> 1.8.0*00(00000000*kWh)
> 1.8.0*99(00000000*kWh)
> 1.8.0*98(00000000*kWh)
> 1.8.0*97(00000000*kWh)
> 1.8.0*96(00000000*kWh)
> 1.8.0*95(00000000*kWh)
> 1.8.0*94(00000000*kWh)
> 1.8.0*93(00000000*kWh)
> 1.8.0*92(00000000*kWh)
> 1.8.0*91(00000000*kWh)
> 1.8.1(00001154*kWh)
> 1.8.1*05(00000674*kWh)
> 1.8.1*04(00000315*kWh)
> 1.8.1*03(00000072*kWh)
> 1.8.1*02(00000004*kWh)
> 1.8.1*01(00000004*kWh)
> 1.8.1*00(00000000*kWh)
> 1.8.1*99(00000000*kWh)
> 1.8.1*98(00000000*kWh)
> 1.8.1*97(00000000*kWh)
> 1.8.1*96(00000000*kWh)
> 1.8.1*95(00000000*kWh)
> 1.8.1*94(00000000*kWh)
> 1.8.1*93(00000000*kWh)
> 1.8.1*92(00000000*kWh)
> 1.8.1*91(00000000*kWh)
> 1.8.2(00000898*kWh)
> 1.8.2*05(00000550*kWh)
> 1.8.2*04(00000224*kWh)
> 1.8.2*03(00000051*kWh)
> 1.8.2*02(00000002*kWh)
> 1.8.2*01(00000002*kWh)
> 1.8.2*00(00000000*kWh)
> 1.8.2*99(00000000*kWh)
> 1.8.2*98(00000000*kWh)
> 1.8.2*97(00000000*kWh)
> 1.8.2*96(00000000*kWh)
> 1.8.2*95(00000000*kWh)
> 1.8.2*94(00000000*kWh)
> 1.8.2*93(00000000*kWh)
> 1.8.2*92(00000000*kWh)
> 1.8.2*91(00000000*kWh)
> 1.25(02.20*kW)
> 31.25(03.48*A)
> 51.25(03.37*A)
> 71.25(03.21*A)
> 32.25(233.8*V)
> 52.25(233.5*V)
> 72.25(232.4*V)
> C.7.1(0005)
> C.7.2(0005)
> C.7.3(0005)
> !
> COUNTER:  1
> /?!
>

**Comment by wiresio** [comment]
Your meter is definitely delivering more values than mine! Which is the value that you are interested in? Replace ‘1.81’ in line 15 with the exact number who want to read out and try again.

**Comment by mawa85** [comment]
I don't know yet, I'm currently figuring out what these values are. 
Is there any documentation about the EHM ITZ interface / output available?

0.0.X are IDs of the device (I removed these from the output in my previous post)

Looks like it reports monthly values (1.8.X0X) and timestamps ( 0.1.20X)

Do you know what these values are:

> 1.25(02.20kW)
> 31.25(03.48A)
> 51.25(03.37A)
> 71.25(03.21A)
> 32.25(233.8V)
> 52.25(233.5V)
> 72.25(232.4*V)
> C.7.1(0005)
> C.7.2(0005)
> C.7.3(0005)

**Comment by wiresio** [comment]
No idea where to find info about your meter. Values you mentioned look like 
1.25 Power
31.25 / 51.25 / 71.25 Current on phase A / B / C
32.25 / 52.25 / 72.25 Voltage on phase A / B / C
